services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node dist/api/index.js
    env_file: .env

  hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - api
    command: node dist/hub/index.js
    env_file: .env

  validator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - hub
    command: node dist/validator/index.js
    env_file: .env
